name: Build and Deploy
on:
  push:
    branches:
      - game
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update apt
        run: | 
          sudo apt update
          sudo apt install cmake libsdl2-dev -y

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.74
          actions-cache-folder: 'emsdk-cache'
      
      - name: build wasm
        run: |
          mkdir build_game
          mkdir build_algo
          mkdir output/algorithm -p
          mkdir output/game -p

          cd build_game
          emcmake cmake .. -DSNEK_ALGORITHM=OFF
          cmake --build .
          cp src/snek* ../output/game

          cd ../build_algo
          emcmake cmake .. -DSNEK_ALGORITHM=ON
          cmake --build .
          cp src/snek* ../output/algorithm

          cd ..
          cp web/level_select.html output/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output 
